# Gitleaks configuration for Google Drive Uploader Action

[allowlist]
  description = "Global allowlist"
  
  # Allowlist the entire CI workflow file since it only contains test data
  [[allowlist.paths]]
  description = "CI workflow file contains test credentials for dry-run mode"
  regex = '''\.github/workflows/ci\.yml$'''
  
  # Allowlist specific test patterns
  [[allowlist.regexes]]
  description = "Base64 encoded dummy test credentials"
  regex = '''ZHVtbXktY3JlZGVudGlhbHMtZm9yLXRlc3Rpbmc='''
  
  [[allowlist.regexes]]
  description = "Dummy credentials pattern"
  regex = '''dummy-.*-[0-9]+'''