name: Google Drive Uploader
description: Upload files or folders to Google Drive
author: Your name or organization here

branding:
  icon: upload-cloud
  color: blue

inputs:
  credentials:
    description: Google Service Account credentials JSON (base64 encoded)
    required: true
  parent-folder-id:
    description: Google Drive folder ID where files will be uploaded
    required: true
  path:
    description: Path to file or folder to upload
    required: true
  name:
    description:
      Optional name for the uploaded file/folder (defaults to original name)
    required: false
  overwrite:
    description: Whether to overwrite existing files with the same name
    required: false
    default: 'false'
  dry-run:
    description:
      Run in dry run mode (simulate upload without actually uploading)
    required: false
    default: 'false'

outputs:
  file-id:
    description:
      Google Drive file ID of the uploaded file (for single file uploads)
  folder-id:
    description:
      Google Drive folder ID of the uploaded folder (for folder uploads)
  uploaded-files:
    description: JSON array of uploaded files with their IDs and paths

runs:
  using: node20
  main: dist/index.js
