name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "This is a test file" > test-file.txt
          mkdir -p test-folder
          echo "File in folder" > test-folder/nested-file.txt

      - name: Test Single File Upload (Dry Run)
        id: test-file-upload
        uses: ./
        with:
          credentials: ZHVtbXktY3JlZGVudGlhbHMtZm9yLXRlc3Rpbmc= # Base64 encoded dummy string
          parent-folder-id: dummy-folder-id-12345
          path: ./test-file.txt
          name: test-upload.txt
          overwrite: 'true'
          dry-run: 'true'

      - name: Test Folder Upload (Dry Run)
        id: test-folder-upload
        uses: ./
        with:
          credentials: ZHVtbXktY3JlZGVudGlhbHMtZm9yLXRlc3Rpbmc= # Base64 encoded dummy string
          parent-folder-id: dummy-folder-id-12345
          path: ./test-folder
          dry-run: 'true'

      - name: Verify outputs
        run: |
          echo "File upload output: ${{ steps.test-file-upload.outputs.file-id }}"
          echo "Folder upload output: ${{ steps.test-folder-upload.outputs.folder-id }}"
          echo "Uploaded files: ${{ steps.test-folder-upload.outputs.uploaded-files }}"
