name: Example - Upload to Google Drive

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload file to Google Drive
        uses: ./
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent-folder-id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          path: README.md
          name: readme-backup.md

  upload-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test folder
        run: |
          mkdir -p test-upload
          echo "Test file 1" > test-upload/file1.txt
          echo "Test file 2" > test-upload/file2.txt
          mkdir -p test-upload/subfolder
          echo "Nested file" > test-upload/subfolder/nested.txt

      - name: Upload folder to Google Drive
        uses: ./
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent-folder-id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          path: test-upload
          overwrite: 'true'
